# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 16 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
    
      - name: ðŸ¦‘ General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}

          user: viitorags
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Sao_Paulo
          config_order: base.header, isocalendar, languages, notable
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit
          plugin_repositories: yes
          plugin_repositories_pinned: 3
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_languages_ignored: html, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, scala, tsq, Tree-sitter Query, lua, nix, ejs, css, shell
          plugin_languages_skipped: nixos-config, dotfiles, nvim
          repositories_skipped: dotfiles, nixos-config, nvim

      - name: ðŸ¦‘ Medias
        uses: lowlighter/metrics@master
        with:
          filename: medias.svg
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: viitorags
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo
          # plugin_activity: yes
          # plugin_activity_days: 14
          # plugin_activity_filter: all
          # plugin_activity_limit: 5
          # plugin_activity_load: 300
          # plugin_activity_visibility: all
          # plugin_achievements: yes
          # plugin_achievements_only: >-
          #   polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #   scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: manga, anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_user: viitorags
          repositories_skipped: dotfiles, nixos-config, nvim, nixdots
